[package]
name = "MicroInsuranceSystem"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }

[addresses]
my_addrx = "268e933516e3938216fafeab56473095b34190145b6c5babb22f0cb073fa11bd"
sys_addrx="0xca10b0176c34f9a8315589ff977645e04497814e9753d21f7d7e7c3d83aa7b57"
std = "0x1"